### ISSUE TITLE
Problem finding bwa index when running ABRA

### ISSUE THREAD

**Issue by mgfield** [mozack/abra#14]
I am trying to run ABRA after using sorting and marking duplicates with PICARD.  In the .log file, it seems that ABRA worked well until it needed to call bwa, and I get the following error in the .log file:

Mon Jan 26 17:23:18 GMT 2015 : Aligning contigs
Running: [bwa mem -t 8 /nethome/mfield/ref_files/hg19.fa abra_temp_dir/all_contigs.fasta > abra_temp_dir/all_contigs.sam]
[E::bwa_idx_load_from_disk] fail to locate the index files
BWA time: 0 seconds.
Exception in thread "main" Stream thread done.
Stream thread done.
java.lang.RuntimeException: BWA exited with non-zero return code : [1] for command: [bwa mem -t 8 /nethome/mfield/ref_files/hg19.fa abra_temp_dir/all_contigs.fasta > abr$
        at abra.Aligner.runCommand(Aligner.java:66)
        at abra.Aligner.align(Aligner.java:36)
        at abra.ReAligner.alignAndCleanContigs(ReAligner.java:485)
        at abra.ReAligner.reAlign(ReAligner.java:188)
        at abra.ReAligner.run(ReAligner.java:1306)
        at abra.Abra.main(Abra.java:12)

I don't understand how to deal with this, as the bwa index files are in the /nethome/mfield/ref_files/ directory, and I am calling the hg19.fa file.  I have the hg19.fa file in my ref_files directory with hg19.amb, hg19.ann, hg19.bwt, hg19.pac, hg19.sa all in that directory as well.   When I call bwa mem separately I am not supposed to use the .fa extension, and I am only supposed to use the hg19 prefix.  But, I think I need to use the .fa extension for the abra calling.  Any ideas what is causing the problem?

**Comment by mozack** [comment]
Did you create the BWA index or was it done for you?  Probably the -p option was used to give the prefix something other than the fasta file name.  I'll add an additional parameter so the BWA index and fasta file can be specified separately.

In the interim, you may wish to move forward with creating an index for hg19.fa without using the -p option.

**Comment by mgfield** [comment]
Yes the problem was that bwa was looking for the prefix hg19, whereas abra needed hg19.fa. So, I had to change all the index files to hg19.fa.bwt, for example, with hg19.fa remaining the same. And then it worked.

**Comment by mozack** [comment]
In v0.91, an optional param --bwa-ref is available for cases where the bwa index prefix does not match the fasta file name.
