### ISSUE TITLE
Running ABRA on BAM files generated from the GATK pepeline

### ISSUE THREAD

**Issue by chisqr** [mozack/abra#19]
I am trying to run ABRA for somatic indel detection. I have BAM files which were aligned using BBMap and were then realigned and quality recalibrated using GATK. 
Will the GATK realignment step have any +ive/-ive effect on the result of ABRA ?

**Comment by mozack** [comment]
I do not believe GATK realignment will have much of an impact on ABRA results.  It is possible IndelRealigner may realign some subset of reads that ABRA does not.  We have not tested this combination much.

In the past, we ran into a couple of cases where BQSR lowered quality around "true" (mismapped) somatic indels causing them to go undetected.  These were clinically validated indels.  We stopped using BQSR for this reason.  Note however, that this is based on anecdotal observations, not rigorous testing.

I've not used BBMap - let me know if you run into issues.
