### ISSUE TITLE
Error while running ABRA

### ISSUE THREAD

**Issue by chisqr** [mozack/abra#20]
Hello, 

 I am tying to run ABRA for a panel data that we have. The command that I am using is:

java -Xmx4G -jar abra-0.94-SNAPSHOT-jar-with-dependencies.jar --in ifile.bam  --out ofile.bam --ref  human_g1k_v37_decoy.fasta  --targets b37.bed --threads 8 --working tmp1 > abra.log 2>&1

The version of bwa is : 0.7.8-r455

This is the error message I am getting:

Done assembling(0): tmp1/15_89394994_89395294_contigs.fasta_k15, 1
Elapsed_msecs_in_NativeAssembler	Region:	15_89394994_89395294	Length:	300	ReadCount:	188	Elapsed	68	Assembled	true	15
Mon Sep 28 19:03:43 CDT 2015 : Processing region: 15_89398655_89399055
Done assembling(0): tmp1/15_89392635_89392995_contigs.fasta_k13, 7
Elapsed_msecs_in_NativeAssembler	Region:	15_89392635_89392995	Length:	360	ReadCount:	213	Elapsed	76	Assembled	true	13
Mon Sep 28 19:03:43 CDT 2015 : Processing region: 15_89398855_89399255
STOPPED_ON_REPEAT: 15_88690509_88690689
Done assembling(0): tmp1/15_88690509_88690689_contigs.fasta_k17, 0
Abra JNI entry point v0.94, prefix: 15_88690509_88690689, read_length: 300, kmer_size: 19, min_node_freq: 2, min_base_qual: 60, min_edge_ratio 0.020000, debug: 1
Assembling: -> tmp1/15_88690509_88690689_contigs.fasta_k19
STOPPED_ON_REPEAT: 15_70976574_70976814
Done assembling(1): tmp1/15_70976574_70976814_contigs.fasta_k43, 0
Elapsed_msecs_in_NativeAssembler	Region:	15_89398855_89399255	Length:	400	ReadCount:	81	Elapsed	11	Assembled	true	301
Mon Sep 28 19:03:43 CDT 2015 : Processing region: 15_89399055_89399455
Abra JNI entry point v0.94, prefix: 15_70976574_70976814, read_length: 300, kmer_size: 45, min_node_freq: 2, min_base_qual: 60, min_edge_ratio 0.020000, debug: 1
Assembling: -> tmp1/15_70976574_70976814_contigs.fasta_k45
STOPPED_ON_REPEAT: 15_85666237_85666477
Done assembling(0): tmp1/15_85666237_85666477_contigs.fasta_k31, 0
Abra JNI entry point v0.94, prefix: 15_85666237_85666477, read_length: 300, kmer_size: 33, min_node_freq: 2, min_base_qual: 60, min_edge_ratio 0.020000, debug: 1
Assembling: -> tmp1/15_85666237_85666477_contigs.fasta_k33
Abra JNI entry point v0.94, prefix: 15_89398655_89399055, read_length: 300, kmer_size: 265, min_node_freq: 2, min_base_qual: 60, min_edge_ratio 0.020000, debug: 1
Elapsed_msecs_in_NativeAssembler	Region:	15_89399055_89399455	Length:	400	ReadCount:	11	Elapsed	9	Assembled	true	301
Mon Sep 28 19:03:43 CDT 2015 : Processing region: 15_89399255_89399655
Assembling: -> tmp1/15_89398655_89399055_contigs.fasta_k265
\#
\# A fatal error has been detected by the Java Runtime Environment:
\#
\#  SIGSEGV (0xb) at pc=0x00007f8a7f6bd46c, pid=18058, tid=140232817727232
\#
\# JRE version: Java(TM) SE Runtime Environment (8.0_20-b26) (build 1.8.0_20-b26)
\# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.20-b23 mixed mode linux-amd64 compressed oops)
\# Problematic frame:
\# C  [libAbra.so+0x2546c]  is_node_in_list(node*, linked_node*)+0x25
\#
\# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
\#
\# An error report file with more information is saved as:
\# hs_err_pid18058.log
Elapsed_msecs_in_NativeAssembler	Region:	15_89399255_89399655	Length:	400	ReadCount:	11	Elapsed	11	Assembled	true	301
Mon Sep 28 19:03:43 CDT 2015 : Processing region: 15_89399455_89399855
\#
\# If you would like to submit a bug report, please visit:
\#   http://bugreport.sun.com/bugreport/crash.jsp
\# The crash happened outside the Java Virtual Machine in native code.
\# See problematic frame for where to report the bug.
\#
Aborted

**Comment by mozack** [comment]
On what OS are you running?

**Comment by chisqr** [comment]
I am using CentOS release 6.7

**Comment by chisqr** [comment]
Here is the output when I use a single thread:

STOPPED_ON_REPEAT: 15_89398455_89398855
Done assembling(0): tmp1/15_89398455_89398855_contigs.fasta_k81, 0
Abra JNI entry point v0.94, prefix: 15_89398455_89398855, read_length: 300, kmer_size: 83, min_node_freq: 2, min_base_qual: 60, min_edge_ratio 0.020000, debug: 1
Assembling: -> tmp1/15_89398455_89398855_contigs.fasta_k83
STOPPED_ON_REPEAT: 15_89398455_89398855
Done assembling(0): tmp1/15_89398455_89398855_contigs.fasta_k83, 0
Abra JNI entry point v0.94, prefix: 15_89398455_89398855, read_length: 300, kmer_size: 85, min_node_freq: 2, min_base_qual: 60, min_edge_ratio 0.020000, debug: 1
Assembling: -> tmp1/15_89398455_89398855_contigs.fasta_k85
STOPPED_ON_REPEAT: 15_89398455_89398855
Done assembling(0): tmp1/15_89398455_89398855_contigs.fasta_k85, 0
Abra JNI entry point v0.94, prefix: 15_89398455_89398855, read_length: 300, kmer_size: 87, min_node_freq: 2, min_base_qual: 60, min_edge_ratio 0.020000, debug: 1
Assembling: -> tmp1/15_89398455_89398855_contigs.fasta_k87
STOPPED_ON_REPEAT: 15_89398455_89398855
Done assembling(0): tmp1/15_89398455_89398855_contigs.fasta_k87, 0
Abra JNI entry point v0.94, prefix: 15_89398455_89398855, read_length: 300, kmer_size: 89, min_node_freq: 2, min_base_qual: 60, min_edge_ratio 0.020000, debug: 1
Assembling: -> tmp1/15_89398455_89398855_contigs.fasta_k89
Done assembling(0): tmp1/15_89398455_89398855_contigs.fasta_k89, 6
Elapsed_msecs_in_NativeAssembler	Region:	15_89398455_89398855	Length:	400	ReadCount:	404	Elapsed	2150	Assembled	true	65
Tue Sep 29 11:16:22 CDT 2015 : Processing region: 15_89398655_89399055
Abra JNI entry point v0.94, prefix: 15_89398655_89399055, read_length: 300, kmer_size: 265, min_node_freq: 2, min_base_qual: 60, min_edge_ratio 0.020000, debug: 1
Assembling: -> tmp1/15_89398655_89399055_contigs.fasta_k265
\#
\# A fatal error has been detected by the Java Runtime Environment:
\#
\#  SIGSEGV (0xb) at pc=0x00007fa07cf9646c, pid=93291, tid=140327268058880
\#
\# JRE version: Java(TM) SE Runtime Environment (8.0_20-b26) (build 1.8.0_20-b26)
\# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.20-b23 mixed mode linux-amd64 compressed oops)
\# Problematic frame:
\# C  [libAbra.so+0x2546c]  is_node_in_list(node*, linked_node*)+0x25
\#
\# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
\#
\# An error report file with more information is saved as:
\# hs_err_pid93291.log
\#
\# If you would like to submit a bug report, please visit:
\#   http://bugreport.sun.com/bugreport/crash.jsp
\# The crash happened outside the Java Virtual Machine in native code.
\# See problematic frame for where to report the bug.
\#
Aborted

**Comment by mozack** [comment]
Would you be able to provide a BAM snippet that reproduces the problem?

**Comment by chisqr** [comment]
Is this issue fixed yet ?

**Comment by mozack** [comment]
Thanks for your patience.  One of the regions in this BAM file appears to have a long repeat, which caused the kmer size to increase beyond the max buffer size causing a buffer overrun.  v0.96 should behave better.

I haven't run ABRA against reads of this length.  Would be interested in hearing how it behaves for you in these cases.  Not sure if assembly will give much additional context.

Please let me know if you run into any more issues.
