### ISSUE TITLE
hidden dependency on bwa mem

### ISSUE THREAD

**Issue by covingto** [mozack/abra#34]
When I run I see that there is a hidden dependency on BWA mem.  Would be nice to be able to specify the path to bwa mem since I might be using different versions.

**Comment by mozack** [comment]
The BWA dependency is clearly documented in the [Running](https://github.com/mozack/abra#running) section of the README.  Not sure that I would consider it hidden.

We are now focused on developing ABRA2 (https://github.com/mozack/abra2).  The dependency on BWA has been removed in this new version.  You might consider using the newer implementation.

If you wish to continue with the original ABRA, I suggest updating your PATH to use the desired BWA version.

**Comment by covingto** [comment]
So it does.  I was looking in the building section.  Will check out abra2.

Thanks
