### ISSUE TITLE
Testing practices

### ISSUE THREAD

**Issue by ionox0** [mozack/abra#40]
Thank you for your work on this project,

I was wondering if you had any suggestions for testing Abra in a pipeline. For example, with a very small pair of fastqs, say only a few reads, are there any parameters or suggestions that would make an Abra run only take a few seconds? Thank you

**Comment by mozack** [comment]
The biggest issue in this case will be loading the reference.  If you can use a small reference, small input bam and a single target region specified in the bed file, the runtime should be in the seconds range.

**Comment by ionox0** [comment]
Great, thanks for the suggestion, yes I think with that change it will be very quick
