### ISSUE TITLE
Abra processes unique reads?

### ISSUE THREAD

**Issue by ionox0** [mozack/abra#41]
I just had a question regarding Abra 0.92, does it realign all reads or only reads that have not had their duplicate flag set by Picard MarkDuplicates? 

Thank you

**Comment by mozack** [comment]
Please see:
https://github.com/mozack/abra/issues/39

Let me  know if you are seeing behavior that indicates otherwise.

**Comment by ionox0** [comment]
Sorry for the duplicate question

And thanks for the help!
