### ISSUE TITLE
abra2 error java.lang.NumberFormatException

### ISSUE THREAD

**Issue by rimzaag** [mozack/abra#44]
Once I try to run ABRA2, I get the following error. Would you please look into it? Thanks.

cmd=java -Xmx16G -jar target/abra2-2.19-jar-with-dependencies.jar --in /path_to/filesample_dedupSort.bam --out /path_to/filesample_abraRealign.bam --ref /path_to/hg19.fasta --threads 8 --targets /path_to/uploads_3091241_Covered-2.bed --tmpdir /path_to/tmpDir

INFO	Fri Jan 18 10:34:36 CET 2019	Abra version: 2.19
INFO	Fri Jan 18 10:34:36 CET 2019	Abra params: [/usr/local/bioinfo/Tools/abra2/target/abra2-2.19-jar-with-dependencies.jar --in /mnt/analyses/KDM-PROD/IOV_baseline/ResVarCall/IOV-KDM_N12enz/alignment/ALN_IOV_IOV_OKDM_IOV_N12enz_dedupSort.bam --out /mnt/analyses/KDM-PROD/IOV_baseline/ResVarCall/IOV-KDM_N12enz/alignment/ALN_IOV_IOV_OKDM_IOV_N12enz_20181012091021_abraRealign.bam --ref /mnt/analyses/Results/Reference/hg19.fasta --threads 8 --targets /mnt/analyses/PROJECT/kdm_IOV/uploads_3091241_Covered-ModifForAbraTest.bed --tmpdir /usr/local/bioinfo/Tools/abra2/tmpRim]
INFO	Fri Jan 18 10:34:36 CET 2019	ABRA version: 2.19
INFO	Fri Jan 18 10:34:36 CET 2019	input0: /mnt/analyses/KDM-PROD/IOV_baseline/ResVarCall/IOV-KDM_N12enz/alignment/ALN_IOV_IOV_OKDM_IOV_N12enz_dedupSort.bam
INFO	Fri Jan 18 10:34:36 CET 2019	output0: /mnt/analyses/KDM-PROD/IOV_baseline/ResVarCall/IOV-KDM_N12enz/alignment/ALN_IOV_IOV_OKDM_IOV_N12enz_20181012091021_abraRealign.bam
INFO	Fri Jan 18 10:34:36 CET 2019	regions: /mnt/analyses/PROJECT/kdm_IOV/uploads_3091241_Covered-ModifForAbraTest.bed
INFO	Fri Jan 18 10:34:36 CET 2019	reference: /mnt/analyses/Results/Reference/hg19.fasta
INFO	Fri Jan 18 10:34:36 CET 2019	num threads: 8
INFO	Fri Jan 18 10:34:36 CET 2019	minEdgeFrequency: 0
minNodeFrequncy: 1
minContigLength: -1
minBaseQuality: 20
minReadCandidateFraction: 0.01
maxAverageRegionDepth: 1000
minEdgeRatio: 0.01

INFO	Fri Jan 18 10:34:36 CET 2019	paired end: true
INFO	Fri Jan 18 10:34:36 CET 2019	isSkipAssembly: false
INFO	Fri Jan 18 10:34:36 CET 2019	useSoftClippedReads: true
INFO	Fri Jan 18 10:34:36 CET 2019	SW scoring: [8, 32, 48, 1]
INFO	Fri Jan 18 10:34:36 CET 2019	Soft clip params: [16, 13, 80, 15]
INFO	Fri Jan 18 10:34:36 CET 2019	Java version: 1.8.0_191
INFO	Fri Jan 18 10:34:36 CET 2019	hostname: bioit-dev
INFO	Fri Jan 18 10:34:36 CET 2019	SG match,mismatch,gap_open_penalty,gap_extend_penalty: 8,-32,-48,-1
INFO	Fri Jan 18 10:34:36 CET 2019	Using temp directory: /usr/local/bioinfo/Tools/abra2/tmpRim/abra2_358def45-c903-44a8-a674-5bc2c317367f1665716855282894176
INFO	Fri Jan 18 10:34:36 CET 2019	Loading native library from: /usr/local/bioinfo/Tools/abra2/tmpRim/abra2_358def45-c903-44a8-a674-5bc2c317367f1665716855282894176/libAbra.so
INFO	Fri Jan 18 10:34:36 CET 2019	Loading reference map:  /mnt/analyses/Results/Reference/hg19.fasta
INFO	Fri Jan 18 10:36:10 CET 2019	Done loading ref map.  Elapsed secs: 93
INFO	Fri Jan 18 10:36:10 CET 2019	Reading Input SAM Header and identifying read length
INFO	Fri Jan 18 10:36:10 CET 2019	Identifying header and determining read length
INFO	Fri Jan 18 10:36:13 CET 2019	Min insert length: 0
INFO	Fri Jan 18 10:36:13 CET 2019	Max insert length: 230110226
INFO	Fri Jan 18 10:36:13 CET 2019	Max read length is: 150
INFO	Fri Jan 18 10:36:13 CET 2019	Min contig length: 151
INFO	Fri Jan 18 10:36:13 CET 2019	Read length: 150
INFO	Fri Jan 18 10:36:13 CET 2019	Loading target regions
INFO	Fri Jan 18 10:36:13 CET 2019	Loading target regions from : /mnt/analyses/PROJECT/kdm_IOV/uploads_3091241_Covered-ModifForAbraTest.bed
INFO	Fri Jan 18 10:36:13 CET 2019	Collapsed regions from 1160 to 1029
INFO	Fri Jan 18 10:36:13 CET 2019	Num regions: 1300
INFO	Fri Jan 18 10:36:13 CET 2019	Total junctions input: 0
INFO	Fri Jan 18 10:36:13 CET 2019	Final Junctions: 0, Variant Junctions: 0
INFO	Fri Jan 18 10:36:13 CET 2019	Intel deflater disabled
INFO	Fri Jan 18 10:36:13 CET 2019	Processing chromosome chunk: chr1_1_25000000
INFO	Fri Jan 18 10:36:13 CET 2019	Processing chromosome chunk: chr1_25000001_50000000
INFO	Fri Jan 18 10:36:13 CET 2019	Processing chromosome chunk: chr1_50000001_75000000
INFO	Fri Jan 18 10:36:13 CET 2019	Processing chromosome chunk: chr1_75000001_100000000
INFO	Fri Jan 18 10:36:13 CET 2019	Processing chromosome chunk: chr1_100000001_125000000
INFO	Fri Jan 18 10:36:13 CET 2019	Processing chromosome chunk: chr1_125000001_150000000
INFO	Fri Jan 18 10:36:13 CET 2019	Processing chromosome chunk: chr1_175000001_200000000
INFO	Fri Jan 18 10:36:13 CET 2019	Processing chromosome chunk: chr1_150000001_175000000
java.lang.NumberFormatException: For input string: "-3,265707"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at abra.ScoredContig.convertAndFilter(ScoredContig.java:53)
	at abra.ReAligner.assemble(ReAligner.java:1114)
	at abra.ReAligner.processRegion(ReAligner.java:1293)
	at abra.ReAligner.processChromosomeChunk(ReAligner.java:361)
	at abra.ReAlignerRunnable.go(ReAlignerRunnable.java:21)
	at abra.AbraRunnable.run(AbraRunnable.java:20)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mozack** [comment]
Please log abra2 issues with the abra2 project:

https://github.com/mozack/abra2

Can you please send me the locale for the machine on which you are running abra2?  i.e. Run the locale command on the command line and send the output.

**Comment by rimzaag** [comment]
Thank you for your reply
output for locale command
>locale
LANG=fr_BE.UTF-8
LANGUAGE=fr_BE:fr
LC_CTYPE="fr_BE.UTF-8"
LC_NUMERIC="fr_BE.UTF-8"
LC_TIME="fr_BE.UTF-8"
LC_COLLATE="fr_BE.UTF-8"
LC_MONETARY="fr_BE.UTF-8"
LC_MESSAGES="fr_BE.UTF-8"
LC_PAPER="fr_BE.UTF-8"
LC_NAME="fr_BE.UTF-8"
LC_ADDRESS="fr_BE.UTF-8"
LC_TELEPHONE="fr_BE.UTF-8"
LC_MEASUREMENT="fr_BE.UTF-8"
LC_IDENTIFICATION="fr_BE.UTF-8"
LC_ALL=

knowing for java i work with java 8
> java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.16.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by mozack** [comment]
This issue is transferred to: https://github.com/mozack/abra2/issues/25
